Clubster\Component\Player\Model\PlayerPosition:
    properties:
        name:
            -   NotBlank:
                    message: clubster.validators.not_blank

            -   Length:
                    max: 256
                    maxMessage: clubster.validators.max_length