framework:
    secret: '%env(APP_SECRET)%'
    default_locale: de
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    #session:
    #    # With this config, PHP's native session handling is used
    #    handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

oneup_flysystem:
    adapters:
        default_local_adapter:
            local:
                directory: public/filesystem
        default_s3_adapter:
            awss3v3:
                client: s3_client
                bucket: scwohlensee
                prefix: ''
    filesystems:
        default:
            adapter: '%filesystem_adapter%'
            alias: League\Flysystem\Filesystem

            # optional - defines the default visibility of the filesystem: `public` or `private`(default)
            visibility: public

