Clubster\Component\Player\Model\Position:
    table: clubster_player_position
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false

        createdAt:
            type: datetime
            nullable: true

        updatedAt:
            type: datetime
            nullable: true
