sylius_resource:
    resources:
        clubster.language:
            classes:
                model: Clubster\Component\Core\Model\Language

        clubster.profile:
            classes:
                model: Clubster\Component\Core\Model\Profile
                form: Clubster\Bundle\CoreBundle\Form\Type\ProfileType
sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: Clubster\Component\Core\Model\AdminUser
                    repository: Clubster\Bundle\CoreBundle\Repository\ORM\AdminUserRepository
                    form: Clubster\Bundle\CoreBundle\Form\Type\AdminUserType
                    controller: Clubster\Bundle\CoreBundle\Controller\UserController
        oauth:
            user:
                #                encoder: false
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController