clubster_admin_dashboard:
    path: /
    methods: [GET]
    defaults:
        _controller: Clubster\Bundle\AdminBundle\Controller\DashboardController:index

clubster_admin_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: Sylius\Bundle\UserBundle\Controller\SecurityController:loginAction
        _sylius:
            template: "@ClubsterAdmin/Security/login.html.twig"
            permission: true
            logged_in_route: clubster_admin_dashboard

clubster_admin_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: Sylius\Bundle\UserBundle\Controller\SecurityController:checkAction

clubster_admin_logout:
    path: /logout
    methods: [GET]
    defaults:
        _controller: Sylius\Bundle\UserBundle\Controller\SecurityController:logoutAction

clubster_admin_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.admin_user:requestPasswordResetTokenAction
        _sylius:
            template: "@ClubsterAdmin/Account/requestPasswordReset.html.twig"
            redirect: clubster_admin_login
            form: Clubster\Bundle\CoreBundle\Form\Type\RequestPasswordResetType

clubster_admin_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.admin_user:resetPasswordAction
        _sylius:
            template: "@ClubsterAdmin/Account/passwordReset.html.twig"
            redirect: clubster_admin_login
            form: Clubster\Bundle\CoreBundle\Form\Type\PasswordResetType

clubster_admin_password:
    path: /profile/password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.admin_user:changePasswordAction
        _sylius:
            template: '@ClubsterAdmin/Account/changePassword.html.twig'

clubster_admin_reset_user:
    path: /users/{id}/reset
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.admin_user:resetUser
