services:
  Clubster\Bundle\CoreBundle\Controller\AuthorizationChecker:
    decorates: sylius.resource_controller.authorization_checker.disabled
    arguments:
      $baseAuthorizationChecker: '@security.authorization_checker'
      $entityManager: '@doctrine.orm.default_entity_manager'
      $requestStack: '@request_stack'

  clubster.fixtures.load:
    class: Clubster\Bundle\CoreBundle\Command\LoadFixturesCommand
    arguments:
      $doctrine: '@doctrine.orm.default_entity_manager'
    tags:
      - { name: console.command }

  clubster.voter.user:
    class: Clubster\Bundle\CoreBundle\Security\Voter\AdminUserVoter
    arguments:
      $decisionManager: '@security.access.decision_manager'
    tags:
      - security.voter

  clubster.voter.language:
    class: Clubster\Bundle\CoreBundle\Security\Voter\LanguageVoter
    arguments:
      $decisionManager: '@security.access.decision_manager'
    tags:
      - security.voter

  clubster.voter.profile:
    class: Clubster\Bundle\CoreBundle\Security\Voter\ProfileVoter
    arguments:
      $decisionManager: '@security.access.decision_manager'
    tags:
      - security.voter

  clubster.menu.admin_builder_main:
    class: Clubster\Bundle\CoreBundle\Menu\MainMenuBuilder
    arguments:
      $factory: '@knp_menu.factory'
      $eventDispatcher: '@event_dispatcher'
      $authorizationChecker: '@security.authorization_checker'
    tags:
      - { name: knp_menu.menu_builder, method: createMenu, alias: clubster.admin.main }

  clubster.grid.filter.fulltext:
    class: Clubster\Bundle\CoreBundle\Grid\Filter\FulltextFilter
    tags:
      -   name: sylius.grid_filter
          type: fulltext
          form_type: Clubster\Bundle\CoreBundle\Form\Type\Filter\FulltextFilterType

  clubster.form.admin_fulltext_filter_type:
    class: Clubster\Bundle\CoreBundle\Form\Type\Filter\FulltextFilterType
    arguments:
      $translator: '@translator'
    tags:
      - form.type