Clubster\Component\Ad\Model\Ad:
    table: clubster_ad
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            nullable: true

        address:
            type: string
            nullable: true

        pictureUrl:
            type: string
            nullable: true

        url:
            type: string
            nullable: true

        createdAt:
            type: datetime
            nullable: true

        updatedAt:
            type: datetime
            nullable: true

    manyToMany:
        types:
            cascade:
                - persist
            targetEntity: Clubster\Component\Ad\Model\AdType
            joinTable:
                name: clubster_ad_ad_type
                joinColumns:
                    ad_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    type_id:
                        referencedColumnName: id
                        unique: true