services:
  clubster.form.player_type:
    class: Clubster\Bundle\PlayerBundle\Form\Type\PlayerType
    tags:
      - form.type

  clubster.form.player_type_type:
    class: Clubster\Bundle\PlayerBundle\Form\Type\PlayerTypeType
    tags:
      - form.type

  clubster.voter.player:
      class: Clubster\Bundle\PlayerBundle\Security\Voter\PlayerVoter
      arguments:
          $decisionManager: '@security.access.decision_manager'
      tags:
        - security.voter