index:
    path: /
    defaults: { _controller: 'App\Controller\IndexController::indexAction' }
team-detail:
    path: /team/detail/{url}
    controller: 'App\Controller\TeamController:detailAction'
news-detail:
    path: /news/detail/{url}
    controller: 'App\Controller\NewsController:detailAction'
page-detail:
    path: /page/detail/{url}
    controller: 'App\Controller\PageController:detailAction'
