index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }
team:
    path: /team
    controller: 'App\Controller\TeamController:indexAction'
team-show:
    path: /team/{id}
    controller: 'App\Controller\TeamController:detailAction'
