index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::indexAction' }
team:
    path: /team
    controller: 'App\Controller\TeamController:indexAction'
team-detail:
    path: /team/{id}
    controller: 'App\Controller\TeamController:detailAction'
news-detail:
    path: /news/{id}
    controller: 'App\Controller\NewsController:detailAction'
