services:
  clubster.form.ad_type:
    class: Clubster\Bundle\AdBundle\Form\Type\AdType
    tags:
      - form.type

  clubster.form.ad_type_type:
    class: Clubster\Bundle\AdBundle\Form\Type\AdTypeType
    tags:
      - form.type

  clubster.voter.ad:
    class: Clubster\Bundle\AdBundle\Security\Voter\AdVoter
    arguments:
      $decisionManager: '@security.access.decision_manager'
    tags:
        - security.voter