services:
  clubster.form.news_Type:
    class: Clubster\Bundle\NewsBundle\Form\Type\NewsType
    tags:
      - form.type

  clubster.form.news_type_type:
    class: Clubster\Bundle\NewsBundle\Form\Type\NewsTypeType
    tags:
      - form.type

  clubster.voter.news:
      class: Clubster\Bundle\NewsBundle\Security\Voter\NewsVoter
      arguments:
          $decisionManager: '@security.access.decision_manager'
      tags:
        - security.voter