clubster_admin_ad:
    resource: |
        alias: clubster.ad
        section: admin
        templates: ClubsterAdminBundle:Crud
        only: ['index', 'update', 'delete', 'create']
        redirect: index
        grid: clubster_admin_ad
        permission: true
        vars:
            all:
                header: clubster.ui.ads
            index:
                subheader: clubster.ui.list_ads
            update:
                subheader: clubster.ui.edit_ad
            create:
                subheader: clubster.ui.create_ad
    type: sylius.resource
