clubster_admin_match:
    resource: |
        alias: clubster.match
        section: admin
        templates: ClubsterAdminBundle:Crud
        only: ['index', 'update', 'delete', 'create']
        redirect: index
        grid: clubster_admin_match
        permission: true
        vars:
            all:
                header: clubster.ui.matches
            index:
                subheader: clubster.ui.list_matches
            update:
                subheader: clubster.ui.edit_match
            create:
                subheader: clubster.ui.create_match
    type: sylius.resource
