clubster_admin_player:
    resource: |
        alias: clubster.player
        section: admin
        templates: ClubsterAdminBundle:Crud
        only: ['index', 'update', 'delete', 'create']
        redirect: index
        grid: clubster_admin_player
        permission: true
        vars:
            all:
                header: clubster.ui.players
            index:
                subheader: clubster.ui.list_players
            update:
                subheader: clubster.ui.edit_player
            create:
                subheader: clubster.ui.create_player
    type: sylius.resource
