Clubster\Component\Core\Model\Team:
    table: clubster_team
    type: entity

    manyToMany:
        news:
            cascade:
                - persist
            targetEntity: Clubster\Component\Core\Model\News
            joinTable:
                name: clubster_news_team
                joinColumns:
                    news_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    team_id:
                        referencedColumnName: id
                        unique: true

    oneToMany:
        matches:
            targetEntity: Clubster\Component\Core\Model\Match
            mappedBy: team

        players:
            targetEntity: Clubster\Component\Core\Model\Player
            mappedBy: team