Clubster\Component\Team\Model\Team:
    table: clubster_team
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false

        description:
            type: string
            nullable: true

        league:
            type: string
            nullable: true

        pictureUrl:
            type: string
            nullable: true

        url:
            type: string
            nullable: true

        gamesUrl:
            type: string
            nullable: true

        resultsUrl:
            type: string
            nullable: true

        createdAt:
            type: datetime
            nullable: true

        updatedAt:
            type: datetime
            nullable: true
