Clubster\Component\News\Model\NewsType:
    table: clubster_news_type
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false

        createdAt:
            type: datetime
            nullable: true

        updatedAt:
            type: datetime
            nullable: true
